// Real UK Run Clubs - Seed Data for Find My Run
// Sources: Great Run, RunTogether, TimeOut, club websites, Instagram

export interface Club {
  id?: string;
  name: string;
  city: string;
  area: string;
  lat: number;
  lng: number;
  day: string;
  time: string;
  distance: string;
  meeting_point: string;
  description: string;
  pace: 'slow' | 'mixed' | 'fast';
  // New fields
  pace_5k?: string;      // e.g. "25-30 mins", "sub-20", "30-35 mins"
  pace_10k?: string;     // e.g. "50-60 mins", "sub-45", "60+ mins"
  terrain: 'road' | 'trail' | 'mixed';
  female_only: boolean;
  influencer_led: boolean;  // Run clubs started by influencers/with big social following
  // Existing fields
  beginner_friendly: boolean;
  dog_friendly: boolean;
  post_run: string | null;
  instagram: string | null;
  website: string | null;
  verified: boolean;
}

export const seedClubs: Club[] = [
  // ============ MANCHESTER ============
  {
    name: "Manchester Road Runners",
    city: "Manchester",
    area: "Castlefield",
    lat: 53.4747,
    lng: -2.2549,
    day: "Wednesday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "The Wharf pub, Castlefield",
    description: "One of Manchester's oldest and biggest running groups. Free to join with 3k, 5k, 7.5k or 10k route options. Sociable group that heads to the pub afterwards.",
    pace: "mixed",
    pace_5k: "25-35 mins",
    pace_10k: "50-70 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "manchesterroadrunners",
    website: "https://groups.runtogether.co.uk/ManchesterRoadRunners",
    verified: true
  },
  {
    name: "Manchester YMCA Harriers",
    city: "Manchester",
    area: "City Centre",
    lat: 53.4794,
    lng: -2.2453,
    day: "Thursday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Outside the Y Club, Manchester",
    description: "Founded in 1882, a friendly and social club in the centre of Manchester. Social group run every Thursday, speedwork on Tuesdays. Open, friendly and accepting to everyone.",
    pace: "mixed",
    pace_5k: "22-35 mins",
    pace_10k: "45-70 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "maboroharriers",
    website: "https://www.manyharrier.co.uk/",
    verified: true
  },
  {
    name: "Manchester Frontrunners",
    city: "Manchester",
    area: "City Centre",
    lat: 53.4808,
    lng: -2.2426,
    day: "Saturday",
    time: "10:00",
    distance: "5-7km",
    meeting_point: "Sackville Gardens",
    description: "LGBTQ+ running club open to everyone. Founded in 2005 as the second ever LGBTQ+ running club in the UK. Supportive, friendly and free.",
    pace: "mixed",
    pace_5k: "25-40 mins",
    pace_10k: "55-80 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "manchesterfrontrunners",
    website: "https://www.manchesterfrontrunners.org/",
    verified: true
  },
  {
    name: "Manchester Run Club",
    city: "Manchester",
    area: "City Centre",
    lat: 53.4831,
    lng: -2.2441,
    day: "Tuesday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "Piccadilly Gardens",
    description: "Established in 2023, a growing community of hundreds of runners. Variety of pace makers for all levels - whether you've never run before or training for an ultra.",
    pace: "mixed",
    pace_5k: "20-40 mins",
    pace_10k: "45-80 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "manchesterrunclub",
    website: "https://manchesterrunclub.com/",
    verified: true
  },
  {
    name: "Didsbury Runners",
    city: "Manchester",
    area: "Didsbury",
    lat: 53.4167,
    lng: -2.2333,
    day: "Tuesday",
    time: "18:45",
    distance: "5-10km",
    meeting_point: "Didsbury Park",
    description: "Not-for-profit club run by volunteers. Motivation is to spread the fun of running and support the running community in South Manchester.",
    pace: "mixed",
    pace_5k: "25-35 mins",
    pace_10k: "50-70 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: true,
    post_run: "Pub",
    instagram: "didsburyrunners",
    website: "https://didsburyrunners.co.uk/",
    verified: true
  },
  {
    name: "Chorlton Runners",
    city: "Manchester",
    area: "Chorlton",
    lat: 53.4408,
    lng: -2.2726,
    day: "Sunday",
    time: "09:00",
    distance: "5-15km",
    meeting_point: "Chorlton Park",
    description: "One of the UK's largest running clubs. Non-members welcome to try Sunday morning runs. Just show up and mingle - no reservation needed.",
    pace: "mixed",
    pace_5k: "22-40 mins",
    pace_10k: "45-80 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: true,
    post_run: "Brunch",
    instagram: "chorltonrunners",
    website: null,
    verified: true
  },
  {
    name: "runtheworldMCR",
    city: "Manchester",
    area: "Salford",
    lat: 53.4875,
    lng: -2.2901,
    day: "Wednesday",
    time: "19:00",
    distance: "5km",
    meeting_point: "Media City, Salford Quays",
    description: "Salford-based running club by women for women. Big focus on safety, mental health and friendship. Mantra: 'no one is too slow'.",
    pace: "slow",
    pace_5k: "30-45 mins",
    pace_10k: "65+ mins",
    terrain: "road",
    female_only: true,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "runtheworldmcr",
    website: null,
    verified: true
  },
  {
    name: "These Girls Can Run MCR",
    city: "Manchester",
    area: "Various",
    lat: 53.4700,
    lng: -2.2400,
    day: "Saturday",
    time: "09:00",
    distance: "5km",
    meeting_point: "Changes weekly - check Instagram",
    description: "Women-only running community focused on building confidence. All abilities welcome. Free coached sessions with qualified run leaders.",
    pace: "slow",
    pace_5k: "30-45 mins",
    pace_10k: "65+ mins",
    terrain: "road",
    female_only: true,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "thesegirlscanrunmcr",
    website: null,
    verified: false
  },

  // ============ LONDON ============
  {
    name: "Run Dem Crew",
    city: "London",
    area: "Spitalfields",
    lat: 51.5194,
    lng: -0.0758,
    day: "Tuesday",
    time: "18:30",
    distance: "5km",
    meeting_point: "Lululemon store, Spitalfields Market",
    description: "Founded in 2007 by Charlie Dark, grown from a small East London group into a diverse community of 500+ runners. Inspired the emergence of Track Mafia, Midnight Runners, and more. The OG crew.",
    pace: "mixed",
    pace_5k: "22-35 mins",
    pace_10k: "45-70 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Social",
    instagram: "rundemcrew",
    website: "https://www.runningcrews.com/crews/run-dem-crew",
    verified: true
  },
  {
    name: "Midnight Runners",
    city: "London",
    area: "Various",
    lat: 51.5145,
    lng: -0.1270,
    day: "Wednesday",
    time: "19:30",
    distance: "10km",
    meeting_point: "Changes weekly - check Instagram",
    description: "Neon lights and a speaker blasting house music. Essentially a party with a 10km warm-up. Social, sweaty, and undeniably cool. One of London's most iconic crews.",
    pace: "fast",
    pace_5k: "20-28 mins",
    pace_10k: "42-58 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: false,
    dog_friendly: false,
    post_run: "Party",
    instagram: "midnightrunners",
    website: "https://www.midnightrunners.com/",
    verified: true
  },
  {
    name: "Track Mafia",
    city: "London",
    area: "East London",
    lat: 51.5350,
    lng: -0.0550,
    day: "Tuesday",
    time: "19:00",
    distance: "Track session",
    meeting_point: "Mile End Stadium",
    description: "Track sessions for runners who want to get faster. Structured workouts with qualified coaches. All abilities welcome but expect to work hard.",
    pace: "fast",
    pace_5k: "18-25 mins",
    pace_10k: "38-52 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: false,
    dog_friendly: false,
    post_run: null,
    instagram: "trackmafia",
    website: null,
    verified: true
  },
  {
    name: "Croissant Run Club",
    city: "London",
    area: "Various",
    lat: 51.5074,
    lng: -0.1278,
    day: "Saturday",
    time: "09:00",
    distance: "4-5km",
    meeting_point: "Changes weekly - different bakery each time",
    description: "Finishes at a different bakery or cafe every week. No racing, no pressure - just easy-paced running with good company and a post-run pastry. The ultimate reward run.",
    pace: "slow",
    pace_5k: "30-40 mins",
    pace_10k: "65+ mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Bakery",
    instagram: "croissantrunclub",
    website: null,
    verified: true
  },
  {
    name: "London City Runners",
    city: "London",
    area: "Bermondsey",
    lat: 51.4979,
    lng: -0.0637,
    day: "Tuesday",
    time: "18:45",
    distance: "5-10km",
    meeting_point: "Bermondsey Beer Mile",
    description: "One of the largest free run clubs in London since 2010. Heavy emphasis on social - responsible for at least 20 marriages and countless friendships!",
    pace: "mixed",
    pace_5k: "22-35 mins",
    pace_10k: "45-70 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "londoncityrunners",
    website: null,
    verified: true
  },
  {
    name: "Hackney Running Club",
    city: "London",
    area: "Hackney",
    lat: 51.5465,
    lng: -0.0554,
    day: "Thursday",
    time: "19:00",
    distance: "6-10km",
    meeting_point: "London Fields Lido, Broadway Market entrance",
    description: "East London vibes. Canal paths, Victoria Park, good energy. Multiple pace groups available.",
    pace: "mixed",
    pace_5k: "22-35 mins",
    pace_10k: "45-70 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "hackneyrunningclub",
    website: null,
    verified: true
  },
  {
    name: "Peckham Pacers",
    city: "London",
    area: "Peckham",
    lat: 51.4745,
    lng: -0.0689,
    day: "Wednesday",
    time: "19:00",
    distance: "5-8km",
    meeting_point: "Eko Brewery, Peckham",
    description: "Motto: 'pints, pizzas and PBs'. Routes finish with a beer on the house at Eko Brewery.",
    pace: "mixed",
    pace_5k: "23-35 mins",
    pace_10k: "48-70 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "peckhampacers",
    website: null,
    verified: true
  },
  {
    name: "These Girls Run London",
    city: "London",
    area: "Battersea",
    lat: 51.4826,
    lng: -0.1464,
    day: "Tuesday",
    time: "18:30",
    distance: "5km",
    meeting_point: "Battersea Power Station",
    description: "All-female running group built on empowerment and support. Two weekly runs plus regular events and socials. A safe space for women of all abilities.",
    pace: "slow",
    pace_5k: "28-40 mins",
    pace_10k: "60+ mins",
    terrain: "road",
    female_only: true,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "thesegirlsrun",
    website: "https://thesegirlsrun.co.uk/",
    verified: true
  },
  {
    name: "Run Dusty",
    city: "London",
    area: "Hackney",
    lat: 51.5400,
    lng: -0.0550,
    day: "Thursday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Changes monthly - independent brewery",
    description: "Relaxed club supporting independent breweries. Easy 5km or 8km before heading to the month's venue for a free pint.",
    pace: "slow",
    pace_5k: "28-38 mins",
    pace_10k: "58-78 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "run.dusty",
    website: null,
    verified: false
  },
  {
    name: "Advent Running",
    city: "London",
    area: "Shoreditch",
    lat: 51.5255,
    lng: -0.0774,
    day: "Monday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "Boxpark Shoreditch",
    description: "East London crew focused on community and wellbeing. Regular runs plus strength sessions and social events. Founded by running influencers.",
    pace: "mixed",
    pace_5k: "22-32 mins",
    pace_10k: "45-65 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Social",
    instagram: "adventrunning",
    website: null,
    verified: true
  },
  {
    name: "Clapham Chasers",
    city: "London",
    area: "Clapham",
    lat: 51.4613,
    lng: -0.1380,
    day: "Wednesday",
    time: "19:00",
    distance: "8-14km",
    meeting_point: "Clapham Common Bandstand",
    description: "South London's fastest. Track sessions and tempo runs for those chasing PBs.",
    pace: "fast",
    pace_5k: "17-24 mins",
    pace_10k: "35-50 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: false,
    dog_friendly: false,
    post_run: null,
    instagram: "claphamchasers",
    website: null,
    verified: true
  },
  {
    name: "Wimbledon Windmilers",
    city: "London",
    area: "Wimbledon",
    lat: 51.4340,
    lng: -0.2140,
    day: "Tuesday",
    time: "19:00",
    distance: "5-12km",
    meeting_point: "Wimbledon Common",
    description: "Trail running on Wimbledon Common. Mix of road and off-road routes through beautiful parkland.",
    pace: "mixed",
    pace_5k: "23-35 mins",
    pace_10k: "48-70 mins",
    terrain: "trail",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: true,
    post_run: "Pub",
    instagram: "wimbledonwindmilers",
    website: null,
    verified: false
  },

  // ============ BIRMINGHAM ============
  {
    name: "City of Birmingham Striders",
    city: "Birmingham",
    area: "City Centre",
    lat: 52.4796,
    lng: -1.9026,
    day: "Tuesday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "Centenary Square",
    description: "Multiple sessions throughout the week. Welcomes runners aiming to improve their performance with structured training.",
    pace: "mixed",
    pace_5k: "20-35 mins",
    pace_10k: "42-70 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "cobstriders",
    website: "https://cobs.org.uk/",
    verified: true
  },
  {
    name: "RunBrumCrew",
    city: "Birmingham",
    area: "City Centre",
    lat: 52.4800,
    lng: -1.8980,
    day: "Wednesday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Victoria Square",
    description: "A 'community' rather than just a running group. Helps you discover your city in a new way. Founded by a marathon-mad run leader. Supportive, friendly and free.",
    pace: "mixed",
    pace_5k: "25-40 mins",
    pace_10k: "52-80 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "runbrumcrew",
    website: null,
    verified: true
  },
  {
    name: "ROCUP Birmingham",
    city: "Birmingham",
    area: "City Centre",
    lat: 52.4796,
    lng: -1.9086,
    day: "Saturday",
    time: "09:00",
    distance: "5km",
    meeting_point: "Centenary Square",
    description: "Rise Over Challenges - a diverse community of 250+ runners. Free 5K runs every Saturday. Emphasizes inclusivity and community spirit.",
    pace: "mixed",
    pace_5k: "25-45 mins",
    pace_10k: "55-90 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "rocupbirmingham",
    website: null,
    verified: false
  },
  {
    name: "Birmingham Swifts",
    city: "Birmingham",
    area: "Cannon Hill",
    lat: 52.4539,
    lng: -1.9042,
    day: "Thursday",
    time: "18:30",
    distance: "5km",
    meeting_point: "Cannon Hill Park",
    description: "The city's free, friendly LGBT+ running group. Open to everyone - new runners particularly welcome. Starting Out sessions plus regular social runs.",
    pace: "slow",
    pace_5k: "28-45 mins",
    pace_10k: "60-90 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "birminghamswifts",
    website: null,
    verified: false
  },
  {
    name: "Well Run Brum",
    city: "Birmingham",
    area: "Various",
    lat: 52.4774,
    lng: -1.8916,
    day: "Saturday",
    time: "09:30",
    distance: "5km",
    meeting_point: "Changes - check Instagram",
    description: "Social running group focused on men's mental wellness. Free fortnightly 5K runs at conversational pace, each beginning with a guest speaker.",
    pace: "slow",
    pace_5k: "30-45 mins",
    pace_10k: "65+ mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "wellrunbrum",
    website: null,
    verified: false
  },
  {
    name: "Lickey Hills Trail Runners",
    city: "Birmingham",
    area: "Lickey Hills",
    lat: 52.3950,
    lng: -2.0100,
    day: "Sunday",
    time: "09:00",
    distance: "8-15km",
    meeting_point: "Lickey Hills Country Park visitor centre",
    description: "Trail running in the beautiful Lickey Hills. Routes vary from 8k to half marathon distance. All abilities welcome.",
    pace: "mixed",
    pace_5k: "25-40 mins",
    pace_10k: "55-80 mins",
    terrain: "trail",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: true,
    post_run: "Coffee",
    instagram: "lickeyhillsrunners",
    website: null,
    verified: false
  },

  // ============ LEEDS ============
  {
    name: "Hyde Park Harriers",
    city: "Leeds",
    area: "Hyde Park",
    lat: 53.8167,
    lng: -1.5667,
    day: "Tuesday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "Hyde Park Corner",
    description: "The friendliest running club in Leeds. Weekly runs grouped by ability, plus whole-club hills, intervals, or strength sessions. Fastest runners to slowest beginners welcome.",
    pace: "mixed",
    pace_5k: "20-40 mins",
    pace_10k: "42-80 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "hydeparkharriers",
    website: "https://www.hydeparkharriers.co.uk/",
    verified: true
  },
  {
    name: "Abbey Runners",
    city: "Leeds",
    area: "Kirkstall",
    lat: 53.8200,
    lng: -1.6000,
    day: "Tuesday",
    time: "18:30",
    distance: "5-12km",
    meeting_point: "Kirkstall Abbey",
    description: "North Leeds club for all abilities and ages. Road, cross-country, fell, trail and triathlon. Pace-based groups Tuesday, structured sessions Thursday.",
    pace: "mixed",
    pace_5k: "20-38 mins",
    pace_10k: "42-78 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "abbeyrunners",
    website: "https://www.abbeyrunners.co.uk/",
    verified: true
  },
  {
    name: "Roundhay Runners",
    city: "Leeds",
    area: "Roundhay",
    lat: 53.8333,
    lng: -1.5000,
    day: "Wednesday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "Roundhay Park Cafe",
    description: "200+ members - you'll find people who match your ability. Events from 5km to five days. Tea, coffee and cakes at the end of Sunday runs.",
    pace: "mixed",
    pace_5k: "22-40 mins",
    pace_10k: "46-80 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: true,
    post_run: "Coffee",
    instagram: "roundhayrunners",
    website: "https://roundhayrunners.co.uk/",
    verified: true
  },
  {
    name: "Dragons Running Club",
    city: "Leeds",
    area: "Yeadon",
    lat: 53.8650,
    lng: -1.6867,
    day: "Tuesday",
    time: "18:45",
    distance: "5-10km",
    meeting_point: "Yeadon Tarn",
    description: "Local, friendly club based in Yeadon. Members run socially and competitively from 5k to 50k. Active social calendar.",
    pace: "mixed",
    pace_5k: "22-38 mins",
    pace_10k: "46-78 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "dragonsrunningclub",
    website: "https://dragonsrunning.co.uk/",
    verified: false
  },
  {
    name: "Crossgates Harriers",
    city: "Leeds",
    area: "Crossgates",
    lat: 53.8167,
    lng: -1.4500,
    day: "Wednesday",
    time: "19:00",
    distance: "10km",
    meeting_point: "Puttstars, The Springs shopping centre",
    description: "Small friendly club in East Leeds. Social run of ~6 miles split into pacing groups. Pace varies from 6 to 13 min/mile. Community Club of the Year winners.",
    pace: "mixed",
    pace_5k: "25-40 mins",
    pace_10k: "52-80 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: null,
    instagram: "crossgatesharriers",
    website: "https://www.crossgatesharriers.com/",
    verified: true
  },
  {
    name: "Leeds Girls Run",
    city: "Leeds",
    area: "City Centre",
    lat: 53.7996,
    lng: -1.5491,
    day: "Thursday",
    time: "18:30",
    distance: "5km",
    meeting_point: "Leeds Dock",
    description: "Women-only running group welcoming all abilities. Safe, supportive space with qualified run leaders. Perfect for those new to running.",
    pace: "slow",
    pace_5k: "30-45 mins",
    pace_10k: "65+ mins",
    terrain: "road",
    female_only: true,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "leedsgirlsrun",
    website: null,
    verified: false
  },

  // ============ BRISTOL ============
  {
    name: "Southville Running Club",
    city: "Bristol",
    area: "Southville",
    lat: 51.4427,
    lng: -2.5983,
    day: "Tuesday",
    time: "18:15",
    distance: "5-10km",
    meeting_point: "Southbank Club, Dean Lane, BS3 1DB",
    description: "Friendly club of mixed abilities for gentle harbourside runs to training sessions. 50p per run. Also runs Thursday evenings.",
    pace: "mixed",
    pace_5k: "23-38 mins",
    pace_10k: "48-78 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "southvillerunningclub",
    website: "https://www.southvillerunningclub.co.uk",
    verified: true
  },
  {
    name: "Clifton Running Club",
    city: "Bristol",
    area: "Clifton",
    lat: 51.4558,
    lng: -2.6214,
    day: "Wednesday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Clifton Village",
    description: "Social running & fitness community since 2012. Making friends & social events at the heart. Part of Social Fitness Bristol family.",
    pace: "mixed",
    pace_5k: "24-36 mins",
    pace_10k: "50-72 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "cliftonrunningclub",
    website: "https://www.cliftonrunningclub.com/",
    verified: true
  },
  {
    name: "Bristol Frontrunners",
    city: "Bristol",
    area: "Queen Square",
    lat: 51.4517,
    lng: -2.5950,
    day: "Wednesday",
    time: "18:45",
    distance: "5-10km",
    meeting_point: "Centre of Queen Square",
    description: "For gender and sexually diverse people and allies. Member of Association of Running Clubs. Two groups: moderate 5k and challenging 8-10k.",
    pace: "mixed",
    pace_5k: "25-40 mins",
    pace_10k: "52-80 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "bristolfrontrunners",
    website: "https://groups.runtogether.co.uk/BristolFrontrunners",
    verified: true
  },
  {
    name: "Leigh Woods Trail Runners",
    city: "Bristol",
    area: "Leigh Woods",
    lat: 51.4550,
    lng: -2.6350,
    day: "Saturday",
    time: "09:00",
    distance: "8-12km",
    meeting_point: "Leigh Woods National Trust car park",
    description: "Trail running through beautiful Leigh Woods. Muddy in winter, stunning in summer. All abilities welcome but expect hills!",
    pace: "mixed",
    pace_5k: "26-42 mins",
    pace_10k: "55-85 mins",
    terrain: "trail",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: true,
    post_run: "Coffee",
    instagram: "leighwoodstrails",
    website: null,
    verified: false
  },
  {
    name: "Run The Ponds",
    city: "Bristol",
    area: "Fishponds",
    lat: 51.4833,
    lng: -2.5333,
    day: "Thursday",
    time: "18:00",
    distance: "5-7.5km",
    meeting_point: "Fishponds Park",
    description: "A 'social run group for all faces and paces'. 5k and 7.5k distances available.",
    pace: "slow",
    pace_5k: "28-42 mins",
    pace_10k: "60-85 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: true,
    post_run: "Pub",
    instagram: "runtheponds",
    website: null,
    verified: false
  },

  // ============ EDINBURGH ============
  {
    name: "Edinburgh Running Network",
    city: "Edinburgh",
    area: "Various",
    lat: 55.9445,
    lng: -3.1892,
    day: "Sunday",
    time: "10:00",
    distance: "5-10km",
    meeting_point: "Changes weekly - check website",
    description: "The friendliest running club in Edinburgh. Regular training sessions tailored to beginners and experienced runners. No one left behind. Tea and cakes after Sunday runs.",
    pace: "mixed",
    pace_5k: "24-42 mins",
    pace_10k: "50-85 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "edinrunnet",
    website: "https://edinburghrunningnetwork.org.uk/",
    verified: true
  },
  {
    name: "We Run Edinburgh",
    city: "Edinburgh",
    area: "City Centre",
    lat: 55.9533,
    lng: -3.1883,
    day: "Wednesday",
    time: "18:30",
    distance: "5-7km",
    meeting_point: "Leith Street x Little King Street (outside St Mary's Cathedral)",
    description: "Where it all started. No sign up needed - just turn up. 5k and 7k guided routes. 'Social Run is not a race. We want your best chat, not your fastest run.'",
    pace: "mixed",
    pace_5k: "25-40 mins",
    pace_10k: "52-80 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "werunedinburgh",
    website: "https://werunedinburgh.com/",
    verified: true
  },
  {
    name: "Edinburgh Frontrunners",
    city: "Edinburgh",
    area: "City Centre",
    lat: 55.9480,
    lng: -3.1890,
    day: "Saturday",
    time: "10:00",
    distance: "5-8km",
    meeting_point: "The Meadows",
    description: "LGBTQIA+ running club for members and allies. Part of a global network with groups in 100+ cities worldwide.",
    pace: "mixed",
    pace_5k: "25-42 mins",
    pace_10k: "52-85 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Brunch",
    instagram: "edinburghfrontrunners",
    website: "https://www.edinburghfrontrunners.org/",
    verified: true
  },
  {
    name: "Carnethy Hill Running Club",
    city: "Edinburgh",
    area: "Pentland Hills",
    lat: 55.8750,
    lng: -3.2500,
    day: "Sunday",
    time: "09:00",
    distance: "10-20km",
    meeting_point: "Various Pentland Hills locations",
    description: "Hill running club based in Edinburgh. Stunning routes in the Pentlands. Experience of trail/hill running recommended.",
    pace: "mixed",
    pace_5k: "22-35 mins",
    pace_10k: "48-75 mins",
    terrain: "trail",
    female_only: false,
    influencer_led: false,
    beginner_friendly: false,
    dog_friendly: false,
    post_run: "Coffee",
    instagram: "carnethyhrc",
    website: "https://carnethy.com/",
    verified: true
  },
  {
    name: "EdinBar Runners",
    city: "Edinburgh",
    area: "The Meadows",
    lat: 55.9400,
    lng: -3.1900,
    day: "Sunday",
    time: "18:00",
    distance: "5km",
    meeting_point: "The Meadows (Middle Meadow Walk)",
    description: "Gentle run followed by a drink and chat. 5k around the Meadows then drinks at a local pub. Also Tuesday sessions at Leith Links.",
    pace: "slow",
    pace_5k: "30-45 mins",
    pace_10k: "65+ mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: null,
    website: "https://www.meetup.com/edinbarrunners/",
    verified: false
  },

  // ============ GLASGOW ============
  {
    name: "Bellahouston Road Runners",
    city: "Glasgow",
    area: "South Side",
    lat: 55.8450,
    lng: -4.3100,
    day: "Tuesday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "Bellahouston Park",
    description: "One of Scotland's largest adult running clubs, 25 years old. Road, cross country and hill running. Action-packed social calendar.",
    pace: "mixed",
    pace_5k: "20-38 mins",
    pace_10k: "42-78 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "bellahoustonrr",
    website: "https://www.bellahoustonroadrunners.co.uk/",
    verified: true
  },
  {
    name: "West End Road Runners",
    city: "Glasgow",
    area: "West End",
    lat: 55.8724,
    lng: -4.2900,
    day: "Wednesday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Kelvingrove Park Bandstand",
    description: "More community group than competitive club. For runners of all ages and stages in Glasgow's West End.",
    pace: "slow",
    pace_5k: "28-45 mins",
    pace_10k: "60-90 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: true,
    post_run: "Pub",
    instagram: "westendroadrunners",
    website: null,
    verified: false
  },
  {
    name: "Wild Trails Running",
    city: "Glasgow",
    area: "Various Parks",
    lat: 55.8250,
    lng: -4.3200,
    day: "Saturday",
    time: "10:00",
    distance: "5-8km",
    meeting_point: "Pollok Park, Linn Park, or Rouken Glen (rotating)",
    description: "Laid-back, inclusive trail running for women (trans inclusive) and non-binary people. Free sessions twice a month.",
    pace: "slow",
    pace_5k: "32-50 mins",
    pace_10k: "70+ mins",
    terrain: "trail",
    female_only: true,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: null,
    instagram: null,
    website: "https://leapsports.org/wild-trails-running",
    verified: false
  },
  {
    name: "Glasgow Frontrunners",
    city: "Glasgow",
    area: "City Centre",
    lat: 55.8600,
    lng: -4.2500,
    day: "Thursday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Glasgow Green",
    description: "LGBTQ+ running club open to everyone. Part of the international Frontrunners network. All abilities welcome.",
    pace: "mixed",
    pace_5k: "25-42 mins",
    pace_10k: "52-85 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "glasgowfrontrunners",
    website: null,
    verified: false
  },

  // ============ OTHER CITIES ============
  {
    name: "Liverpool Running Bugs",
    city: "Liverpool",
    area: "Baltic Triangle",
    lat: 53.3964,
    lng: -2.9850,
    day: "Monday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Baltic Market entrance",
    description: "Docklands and street art routes. Liverpool's friendliest run club.",
    pace: "mixed",
    pace_5k: "24-38 mins",
    pace_10k: "50-78 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Food market",
    instagram: "liverpoolrunningbugs",
    website: null,
    verified: true
  },
  {
    name: "Run Liverpool",
    city: "Liverpool",
    area: "Albert Dock",
    lat: 53.4010,
    lng: -2.9920,
    day: "Wednesday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "Albert Dock",
    description: "City centre runs along the waterfront. Multiple pace groups available. Growing community of 300+ runners.",
    pace: "mixed",
    pace_5k: "22-38 mins",
    pace_10k: "46-78 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "runliverpool",
    website: null,
    verified: false
  },
  {
    name: "Steel City Striders",
    city: "Sheffield",
    area: "Endcliffe",
    lat: 53.3714,
    lng: -1.5112,
    day: "Wednesday",
    time: "18:30",
    distance: "5-12km",
    meeting_point: "Endcliffe Park Cafe",
    description: "Hills are mandatory in Sheffield! Multiple groups from social to speedy. One of Sheffield's most popular clubs.",
    pace: "mixed",
    pace_5k: "22-40 mins",
    pace_10k: "46-80 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: true,
    post_run: "Pub",
    instagram: "steelcitystriders",
    website: null,
    verified: true
  },
  {
    name: "Peak District Trail Runners",
    city: "Sheffield",
    area: "Peak District",
    lat: 53.3500,
    lng: -1.6000,
    day: "Sunday",
    time: "09:00",
    distance: "10-25km",
    meeting_point: "Various Peak District locations",
    description: "Trail and fell running in the stunning Peak District. Long runs on Sundays, shorter midweek sessions. Experience required.",
    pace: "mixed",
    pace_5k: "22-35 mins",
    pace_10k: "48-72 mins",
    terrain: "trail",
    female_only: false,
    influencer_led: false,
    beginner_friendly: false,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "peakdistricttrails",
    website: null,
    verified: false
  },
  {
    name: "Tyne Bridge Harriers",
    city: "Newcastle",
    area: "Quayside",
    lat: 54.9695,
    lng: -1.6010,
    day: "Tuesday",
    time: "18:00",
    distance: "6-10km",
    meeting_point: "Gateshead Millennium Bridge (Newcastle side)",
    description: "Iconic bridge crossings and quayside miles. Geordie hospitality guaranteed.",
    pace: "mixed",
    pace_5k: "22-38 mins",
    pace_10k: "46-78 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "tynebridgeharriers",
    website: null,
    verified: true
  },
  {
    name: "Newcastle Frontrunners",
    city: "Newcastle",
    area: "City Centre",
    lat: 54.9750,
    lng: -1.6140,
    day: "Saturday",
    time: "10:00",
    distance: "5-8km",
    meeting_point: "Grey's Monument",
    description: "LGBTQ+ running club for all abilities. Friendly, supportive group exploring Newcastle on foot.",
    pace: "mixed",
    pace_5k: "26-45 mins",
    pace_10k: "55-90 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Brunch",
    instagram: "newcastlefrontrunners",
    website: null,
    verified: false
  },
  {
    name: "Nottingham Run Crew",
    city: "Nottingham",
    area: "City Centre",
    lat: 52.9548,
    lng: -1.1581,
    day: "Tuesday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Old Market Square",
    description: "Nottingham's social running community. Free runs every Tuesday with multiple pace groups.",
    pace: "mixed",
    pace_5k: "23-40 mins",
    pace_10k: "48-80 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "nottinghamruncrew",
    website: null,
    verified: false
  },
  {
    name: "Brighton & Hove Run Crew",
    city: "Brighton",
    area: "Seafront",
    lat: 50.8225,
    lng: -0.1372,
    day: "Wednesday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "Brighton Palace Pier",
    description: "Seafront runs with stunning views. Multiple pace groups from social joggers to speedsters.",
    pace: "mixed",
    pace_5k: "22-38 mins",
    pace_10k: "46-78 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "brightonruncrew",
    website: null,
    verified: false
  },
  {
    name: "Oxford Run Club",
    city: "Oxford",
    area: "City Centre",
    lat: 51.7520,
    lng: -1.2577,
    day: "Thursday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Radcliffe Camera",
    description: "Run through Oxford's historic streets and along the river. Open to students, residents and visitors.",
    pace: "mixed",
    pace_5k: "24-40 mins",
    pace_10k: "50-80 mins",
    terrain: "mixed",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "oxfordrunclub",
    website: null,
    verified: false
  },
  {
    name: "Cambridge Run Club",
    city: "Cambridge",
    area: "City Centre",
    lat: 52.2053,
    lng: 0.1218,
    day: "Wednesday",
    time: "18:30",
    distance: "5-8km",
    meeting_point: "Parker's Piece",
    description: "Explore Cambridge on foot. Routes along the river and through the colleges. All welcome.",
    pace: "mixed",
    pace_5k: "23-38 mins",
    pace_10k: "48-78 mins",
    terrain: "road",
    female_only: false,
    influencer_led: false,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "cambridgerunclub",
    website: null,
    verified: false
  },
  {
    name: "Cardiff Run Club",
    city: "Cardiff",
    area: "Cardiff Bay",
    lat: 51.4653,
    lng: -3.1657,
    day: "Tuesday",
    time: "18:30",
    distance: "5-10km",
    meeting_point: "Wales Millennium Centre",
    description: "Wales' capital running community. Bay runs and city routes. Growing fast with 200+ members.",
    pace: "mixed",
    pace_5k: "23-40 mins",
    pace_10k: "48-80 mins",
    terrain: "road",
    female_only: false,
    influencer_led: true,
    beginner_friendly: true,
    dog_friendly: false,
    post_run: "Pub",
    instagram: "cardiffrunclub",
    website: null,
    verified: false
  },
];

// City data for pages and map
export const cities = [
  { slug: 'manchester', name: 'Manchester', lat: 53.4808, lng: -2.2426, description: 'A thriving run club scene from Castlefield to Didsbury' },
  { slug: 'london', name: 'London', lat: 51.5074, lng: -0.1278, description: 'Home to legendary crews like Run Dem and Midnight Runners' },
  { slug: 'birmingham', name: 'Birmingham', lat: 52.4862, lng: -1.8904, description: 'The Midlands hub with clubs for every runner' },
  { slug: 'leeds', name: 'Leeds', lat: 53.8008, lng: -1.5491, description: 'Yorkshire running from Hyde Park to Roundhay' },
  { slug: 'bristol', name: 'Bristol', lat: 51.4545, lng: -2.5879, description: 'Harbourside jogs and Clifton hills' },
  { slug: 'edinburgh', name: 'Edinburgh', lat: 55.9533, lng: -3.1883, description: 'Historic routes through Scotland\'s capital' },
  { slug: 'glasgow', name: 'Glasgow', lat: 55.8642, lng: -4.2518, description: 'Friendly clubs across Scotland\'s biggest city' },
  { slug: 'liverpool', name: 'Liverpool', lat: 53.4084, lng: -2.9916, description: 'Dockland runs and Scouse hospitality' },
  { slug: 'sheffield', name: 'Sheffield', lat: 53.3811, lng: -1.4701, description: 'Hills, trails and Steel City spirit' },
  { slug: 'newcastle', name: 'Newcastle', lat: 54.9783, lng: -1.6178, description: 'Quayside miles and Tyne bridges' },
  { slug: 'nottingham', name: 'Nottingham', lat: 52.9548, lng: -1.1581, description: 'Robin Hood country running' },
  { slug: 'brighton', name: 'Brighton', lat: 50.8225, lng: -0.1372, description: 'Seafront runs and South Downs trails' },
  { slug: 'oxford', name: 'Oxford', lat: 51.7520, lng: -1.2577, description: 'Historic streets and river paths' },
  { slug: 'cambridge', name: 'Cambridge', lat: 52.2053, lng: 0.1218, description: 'College runs and riverside routes' },
  { slug: 'cardiff', name: 'Cardiff', lat: 51.4816, lng: -3.1791, description: 'Wales\' running capital' },
];

// Pace guide for filters
export const paceGuide = {
  '5k': [
    { label: 'Sub 20', value: 'sub-20', description: 'Elite/fast club runners' },
    { label: '20-25 mins', value: '20-25', description: 'Fast recreational' },
    { label: '25-30 mins', value: '25-30', description: 'Good club pace' },
    { label: '30-35 mins', value: '30-35', description: 'Social/steady' },
    { label: '35+ mins', value: '35+', description: 'Beginner/relaxed' },
  ],
  '10k': [
    { label: 'Sub 45', value: 'sub-45', description: 'Elite/fast club runners' },
    { label: '45-55 mins', value: '45-55', description: 'Fast recreational' },
    { label: '55-65 mins', value: '55-65', description: 'Good club pace' },
    { label: '65-75 mins', value: '65-75', description: 'Social/steady' },
    { label: '75+ mins', value: '75+', description: 'Beginner/relaxed' },
  ],
};
