// Comprehensive list of UK cities and major towns
// Organized alphabetically for easy lookup

export const ukCities = [
  // England - Major Cities
  'Bath',
  'Birmingham',
  'Bradford',
  'Brighton',
  'Bristol',
  'Cambridge',
  'Canterbury',
  'Carlisle',
  'Chelmsford',
  'Chester',
  'Chichester',
  'Colchester',
  'Coventry',
  'Derby',
  'Doncaster',
  'Durham',
  'Ely',
  'Exeter',
  'Gloucester',
  'Hereford',
  'Kingston upon Hull',
  'Lancaster',
  'Leeds',
  'Leicester',
  'Lichfield',
  'Lincoln',
  'Liverpool',
  'London',
  'Manchester',
  'Milton Keynes',
  'Newcastle upon Tyne',
  'Norwich',
  'Nottingham',
  'Oxford',
  'Peterborough',
  'Plymouth',
  'Portsmouth',
  'Preston',
  'Ripon',
  'Salford',
  'Salisbury',
  'Sheffield',
  'Southampton',
  'Southend-on-Sea',
  'St Albans',
  'Stoke-on-Trent',
  'Sunderland',
  'Truro',
  'Wakefield',
  'Wells',
  'Westminster',
  'Winchester',
  'Wolverhampton',
  'Worcester',
  'York',

  // England - Large Towns
  'Basingstoke',
  'Bedford',
  'Blackburn',
  'Blackpool',
  'Bolton',
  'Bournemouth',
  'Bracknell',
  'Bromley',
  'Burnley',
  'Burton upon Trent',
  'Bury',
  'Cheltenham',
  'Chesterfield',
  'Crawley',
  'Croydon',
  'Darlington',
  'Dudley',
  'Eastbourne',
  'Gateshead',
  'Gillingham',
  'Grimsby',
  'Guildford',
  'Halifax',
  'Harlow',
  'Harrogate',
  'Hastings',
  'Hemel Hempstead',
  'High Wycombe',
  'Huddersfield',
  'Ipswich',
  'Keighley',
  'Kidderminster',
  'Leamington Spa',
  'Loughborough',
  'Luton',
  'Maidstone',
  'Mansfield',
  'Margate',
  'Middlesbrough',
  'Northampton',
  'Nuneaton',
  'Oldham',
  'Poole',
  'Reading',
  'Redditch',
  'Rochdale',
  'Rotherham',
  'Royal Tunbridge Wells',
  'Rugby',
  'Scarborough',
  'Scunthorpe',
  'Shrewsbury',
  'Slough',
  'Solihull',
  'Stafford',
  'Stevenage',
  'Stockport',
  'Stockton-on-Tees',
  'Sutton Coldfield',
  'Swindon',
  'Tamworth',
  'Taunton',
  'Telford',
  'Thanet',
  'Torquay',
  'Walsall',
  'Warrington',
  'Watford',
  'West Bromwich',
  'Weston-super-Mare',
  'Wigan',
  'Woking',
  'Worthing',
  'Yeovil',

  // Scotland
  'Aberdeen',
  'Dundee',
  'Dunfermline',
  'East Kilbride',
  'Edinburgh',
  'Falkirk',
  'Glasgow',
  'Hamilton',
  'Inverness',
  'Kilmarnock',
  'Kirkcaldy',
  'Livingston',
  'Paisley',
  'Perth',
  'Stirling',

  // Wales
  'Bangor',
  'Cardiff',
  'Newport',
  'St Davids',
  'Swansea',
  'Wrexham',

  // Northern Ireland
  'Armagh',
  'Belfast',
  'Derry',
  'Lisburn',
  'Newry',

  // Other option for unlisted locations
  'Other',
].sort((a, b) => {
  // Keep "Other" at the end
  if (a === 'Other') return 1;
  if (b === 'Other') return -1;
  return a.localeCompare(b);
});

// Export count for reference
export const cityCount = ukCities.length - 1; // Excluding "Other"
